### ISSUE TITLE
readme and utils have different write functions

### ISSUE THREAD

**Issue by zachheiner** [byuitechops/city-organizer#1]
In your example you have a write function that uses `fs.createWriteStream`. In the Utils directory you provide a write function that uses `fs.writeFileSync`. Most new hires won't notice this difference and will try to use `fs.readFileSync` as `fs.createWriteStream`

**Comment by benjameep** [comment]
Extracted the create markdown file logic to the `write` function

**Comment by meeple142** [comment]
No working today!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
